// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrialTrack.Data;

#nullable disable

namespace TrialTrack.Migrations
{
    [DbContext(typeof(TrialTrackDbContext))]
    [Migration("20260919163819_AddSubjectsAndRecruitmentTracking")]
    partial class AddSubjectsAndRecruitmentTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrialTrack.Models.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudyId");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("TrialTrack.Models.Study", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("FinalRandomisationDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProtocolNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly?>("RecruitmentStartDate")
                        .HasColumnType("date");

                    b.Property<int?>("RecruitmentTarget")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ScreeningCloseDate")
                        .HasColumnType("date");

                    b.Property<int?>("ScreeningWindowDays")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProtocolNumber")
                        .IsUnique();

                    b.ToTable("Studies");
                });

            modelBuilder.Entity("TrialTrack.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("PreScreenDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("RandomisationDate")
                        .HasColumnType("date");

                    b.Property<string>("RecruitmentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ScreenFailDate")
                        .HasColumnType("date");

                    b.Property<string>("ScreenFailReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ScreeningDate")
                        .HasColumnType("date");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.HasIndex("SubjectNumber")
                        .IsUnique();

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("TrialTrack.Models.Site", b =>
                {
                    b.HasOne("TrialTrack.Models.Study", "Study")
                        .WithMany("Sites")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("TrialTrack.Models.Subject", b =>
                {
                    b.HasOne("TrialTrack.Models.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("TrialTrack.Models.Study", b =>
                {
                    b.Navigation("Sites");
                });
#pragma warning restore 612, 618
        }
    }
}
